### ISSUE TITLE
Sort order, date input and picture width

### ISSUE THREAD

**Issue by merlin699** [m1k1o/blog#44]
Thanks for this great pice of software. It's pretty much perfect for my little blog, but I have three questions.
This is in no way a change request, just questions if it's easily achievable, or maybe it already possible and I just don't know it.
1. is it possible to reverse the sort order? The default order is quite perfect, but if someone wants to view the complete history of my project, it would be nice to have the order reversed (oldest first). Something like `url.com/sort=reverse`, the link then should be located in the cover (head-banner).
2. to change the date doesnt let you change the year. It's only doable through changing the month. The first picture in my blog is from 01/1993 - this was a lot of clicking going back 30 years. Would it be possible to make the year clickable (changable) in the date-picker?
3. I'd love to increase the width of each post to the size of the head-banner. I managed to extend the box size with mounting the modified css to the corresponding path, but this doesn't workfor the pictures itself, thy remain 476px. Would this be easily achievable, maybe by myself?

Thx a lot!

**Comment by m1k1o** [comment]
Thanks for using it.

1. Order is now [hardcoded here](https://github.com/m1k1o/blog/blob/6f5e59f1401c4a3cf2e518aa85b231ea14e8a2ef/app/post.class.php#L452) but it could be easily added along with existing filters. **Implemented.**
2. You are right. Initally it was just set of dropdowns that allowed changing year but then it was changed and the option was not included. That would be a nice addition. Or adding new set of arrows `<<` and `>>` that would just change years. While it can be lot of clicking again if that date is quite old. **Implemented.**
3. Thumbnail size is currenty [hardcoded here](https://github.com/m1k1o/blog/blob/6f5e59f1401c4a3cf2e518aa85b231ea14e8a2ef/app/image.class.php#L6-L7), you could change it to whatever you need and then just rebuild the docker image.

Thank you for your ideas! When I find time, I might look at them. I specifically like the sorting option since that could be wasy addition and would help a lot to explore the older posts.

**Comment by m1k1o** [comment]
This is how it would look like:
![image](https://user-images.githubusercontent.com/7534274/214361601-ebd37f58-a54e-44f2-80b3-575ae97d385b.png)

**Comment by merlin699** [comment]
Thanks a lot, awesome work!
